name: Hello World
description: Greet someone

inputs:
  who-to-greet:
    description: Who to Greet
    required: true
    default: World

outputs:
  random-number:
    description: Random Number
    value: ${{ steps.action.outputs.random-number }}

runs:
  using: composite
  steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - id: action
      run: |
        i=$(echo "${{ toJSON(inputs) }}" )
        go run main.go -inputs $i
      working-directory: ${{ github.action_path }}
      shell: bash
