name: Hello World
description: Greet someone

inputs:
  who-to-greet:
    description: Who to Greet
    required: true
    default: World

outputs:
  random-number:
    description: Random Number
    value: ${{ steps.action.outputs.random-number }}

runs:
  using: composite
  steps:
    - id: action
      run: go run main.go -inputs '${{ toJSON(inputs) }}'
      working-directory: ${{ github.action_path }}
      shell: bash