name: Enforce Security SLA
description: Block PRs that have security vulnerabilities that exceed the SLA

inputs:
  critical-threshold:
    description: SLA for remediation of critical vulnerabilities (in days)
    required: false
    default: "7"
  high-threshold:
    description: SLA for remediation of high vulnerabilities (in days)
    required: false
    default: "14"
  medium-threshold:
    description: SLA for remediation of medium vulnerabilities (in days)
    required: false
    default: "30"
  low-threshold:
    description: SLA for remediation of low vulnerabilities (in days)
    required: false
    default: "60"

runs:
  using: composite
  steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - id: action
      run: go run main.go -inputs '${{ toJSON(inputs) }}'
      working-directory: ${{ github.action_path }}
      shell: bash
