name: Security

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "44 22 * * 0"

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [go]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  enforce-security-sla:
    name: Enforce Security SLA
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.SECURITY_APP_ID }}
          private-key: ${{ secrets.SECURITY_APP_PRIVATE_KEY }}

      - id: security-sla
        uses: underopsco/enforce-security-sla-action@main
        with:
          token: ${{ steps.app-token.outputs.token }}
